swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:



  /api/Application/:
    get:
      tags:
        - Applications
      summary: Get a list of all applicatiom
      description: For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
      operationId: create_application
      produces:
        - application/json 
      responses:
        '200':
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found

    post:
      tags:
        - Applications
      summary: Create a new application record
      description: insert into the database
      operationId: getOrderById
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ID of Administrators that needs to be fetched
          required: true
          type: integer
          maximum: 10
          minimum: 1
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
        '404': 
          description: Order not found


  /api/Applicants/:
    get:
      tags:
        - Applicants
      summary: Retrieve a list of all  applicants in the system
      description: For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
      operationId: get_applicants
      produces:
        - application/json 
      parameters:
        - name: name
        #  in: path
          description: name of applicant
          required: false
          type: str
        #  maximum: 10
        #  minimum: 1
        #  format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found

    post:
      tags:
        - Applicants
      summary: Create a new applicant record 
      description: For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
      operationId: new_applicant
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: ID of Administrators that needs to be fetched
          required: true
          type: integer
          maximum: 10
          minimum: 1
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found


  /api/schemes/:
    get:
      tags:
        - Schemes
      summary: Get a list of all  schemes
      description: For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
      operationId: getOrderById
      produces:
        - application/json 
      parameters:
        - name: orderId
          in: path
          description: ID of Administrators that needs to be fetched
          required: true
          type: integer
          maximum: 10
          minimum: 1
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found

  /api/schemes/eligible/:
    get:
      tags:
        - Schemes
      summary: Get a list schemes eligible
      description: For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
      operationId: getOrderById
      produces:
        - application/json 
      parameters: 
        - name: orderId
          in: path
          description: ID of Administrators that needs to be fetched
          required: true
          type: integer
          maximum: 10
          minimum: 1
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found

